<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Apprendre les principales fonctionnalités de COGugaison • COGugaison</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Apprendre les principales fonctionnalités de COGugaison">
<meta property="og:description" content="COGugaison">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">COGugaison</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.4</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../articles/COGugaison.html">Introduction à COGugaison</a>
</li>
<li>
  <a href="../reference/index.html">Documentation des fonctions</a>
</li>
<li>
  <a href="../news/index.html">Nouveautés</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="http://github.com/antuki/COGugaison/">
    <span class="fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="COGugaison_files/header-attrs-2.9.1/header-attrs.js"></script><script src="COGugaison_files/htmlwidgets-1.5.3/htmlwidgets.js"></script><link href="COGugaison_files/vis-4.20.1/vis.css" rel="stylesheet">
<script src="COGugaison_files/vis-4.20.1/vis.min.js"></script><script src="COGugaison_files/visNetwork-binding-2.0.9/visNetwork.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Apprendre les principales fonctionnalités de COGugaison</h1>
                        <h4 class="author">antuki</h4>
            
      
      <small class="dont-index">Source: <a href="http://github.com/antuki/COGugaison/blob/master/vignettes/COGugaison.Rmd"><code>vignettes/COGugaison.Rmd</code></a></small>
      <div class="hidden name"><code>COGugaison.Rmd</code></div>

    </div>

    
    
<div id="introduction-à-cogugaison" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction-%C3%A0-cogugaison" class="anchor"></a>Introduction à COGugaison</h2>
<p>Nous allons balayer dans cette vignette les principales fonctionnalités du package <code>COGugaison</code>.</p>
<p>Le découpage des territoires français, en particulier les communes, n’est pas un phénomène immuable. Chaque année certaines communes changent de codes, ou bien de nom, fusionnent ou encore se divisent. Certains périmètres supra-communaux changent également, comme celui des cantons qui a été récemment redéfini. C’est à l’Insee que revient le suivi de ces changements afin d’établir chaque année le code officiel géographique (COG).</p>
<p>Ce package R a alors pour objectif global de manipuler des données communales produites à différents millésimes et de les agréger à différents niveaux supra-communaux. Plus précisément, il permet actuellement de :</p>
<ul>
<li>détecter le millésime du code officiel géographique d’une table de données communales : fonction <code>COG_akinator</code>, faire un diagnostic de COG plus détaillé avec <code>diag_COG</code> et apparier une liste de communes d’une base de données avec celle du COG d’un millésime donné avec <code>apparier_COG</code>
</li>
<li>visualiser les modifications communales (fusions, défusions, changements de codes ou de noms) qui ont eu lieu entre deux dates : <code>modifications_communales</code><br>
</li>
<li>visualiser sur un graphique interactif la trajectoire d’une commune donnée, c’est-à-dire toutes les modifications qui ont eu lieu depuis 1968 : <code>trajectoire_commune</code> et <code>trajectoire_commune_shiny</code>.</li>
<li>transformer des tables de données numériques en géographie au premier janvier d’une année souhaitée : <code>changement_COG_varNum</code>.</li>
<li>transformer des typologies de communes en géographie au premier janvier d’une année souhaitée en ayant le choix entre plusieurs hypothèses de classement en cas de fusion de communes de classes différentes (attribuer une unique classe à toutes les communes fusionnées, attribuer la classe qui contient le plus de population, définir une classe absorbante, une classe absorbée ou une classe spécifique aux regroupements de plusieurs communes de classes différentes) : <code>changement_COG_typo</code>. Il est également possible d’isoler dans une table les communes fusionnées appartenant à des classes différentes : <code>changement_COG_typo_details</code>.</li>
<li>permettre d’agréger les tables de données communales à de nombreux échelons supra-communaux administratifs (EPCI, arrondissements, cantons-villes, départements, régions) ou d’étude (bassins de vie, zones d’emploi, unités urbaines, aires urbaines) : <code>nivsupra</code>.</li>
<li>gérer des cas particuliers comme les codes Insee des communes corses (<code>modification_Corse</code>) ou des arrondissements municipaux de Paris, Lyon, et Marseille (<code>enlever_PLM</code>) ou encore l’ancienne commune de l’Oudon (<code>modification_Oudon</code>)</li>
</ul>
<p>Il est important de souligner que les données utilisées ici s’appuient sur des tables publiées par l’Insee :</p>
<ul>
<li><a href="https://www.insee.fr/fr/information/2666684#titre-bloc-11">l’historique des géographies communales</a></li>
<li><a href="https://www.insee.fr/fr/information/2028028">les tables d’appartenance des communes aux différents niveaux géographiques</a></li>
</ul>
<p>Il est évidemment conseillé de se référer aux données officielles de l’Insee en cas de doute sur un résultat.</p>
<p>Commençons par installer le package <code>COGugaison</code> et à le charger dans R.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co">#devtools::install_github("antuki/COGugaison")</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://github.com/antuki/COGugaison">COGugaison</a></span><span class="op">)</span></code></pre></div>
<pre><code>## Afin de mieux connaitre les utilisateurs des packages COGugaison et CARTElette et de mieux repondre a vos besoins, merci de repondre a cette rapide enquete en ligne :
## https://antuki.github.io/2019/11/08/opinion_package/</code></pre>
<p>Le millésime le plus récent contenu dans le package peut être visualisé de la manière suivante :</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">COGugaison</span><span class="fu">:::</span><span class="va">annee_ref</span></code></pre></div>
<pre><code>## [1] 2021</code></pre>
</div>
<div id="les-bases-de-données-utiles-dans-cogugaison" class="section level2">
<h2 class="hasAnchor">
<a href="#les-bases-de-donn%C3%A9es-utiles-dans-cogugaison" class="anchor"></a>Les bases de données utiles dans COGugaison</h2>
<p>En plus de contenir des fonctions permettant la gestion des codes officiels géographiques, COGugaison contient également, dans des Rdata, des bases de données qui peuvent vous être également utiles par ailleurs.</p>
<blockquote>
<ul>
<li>COG</li>
</ul>
</blockquote>
<p>Ce Rdata contient des data.frame (tables de données) intitulés COGXXXX, XXXX étant à remplacer par une année de COG donnée. Les tables intitulées COGXXXX_insee correspondent à des tables selon le COG pris en compte par l’Insee dans la diffusion de ses données (qui est presque identique au COG à quelques exceptions près listées dans la documentation).</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">COG2017</span><span class="op">)</span></code></pre></div>
<pre><code>##   CODGEO                  LIBGEO   POP
## 1  01001 L'Abergement-Clémenciat   767
## 2  01002   L'Abergement-de-Varey   241
## 3  01004       Ambérieu-en-Bugey 14127
## 4  01005     Ambérieux-en-Dombes  1619
## 5  01006                 Ambléon   109
## 6  01007                Ambronay  2615</code></pre>
<p>Les variables des tables sont les suivantes :</p>
<ul>
<li>CODGEO contient le code Insee des communes</li>
<li>LIBGEO contient le nom des communes</li>
<li>POP contient la population de référence de la commune selon l’année du COG</li>
</ul>
<blockquote>
<ul>
<li>TABLES_PASSAGE</li>
</ul>
</blockquote>
<p>Ce Rdata contient des data.frame intitulées PASSAGE_XXXX_YYYY, XXXX et YYYY étant à remplacer par des années de COG données. Il s’agit de tables de passages permettant de passer d’un COG à un autre (plus récent ou plus ancien). Le suffixe "_insee" correspond également à des tables qui tiennent compte des COG pris en compte par l’Insee.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">PASSAGE_2015_2016_insee</span><span class="op">)</span></code></pre></div>
<pre><code>##   cod2015 cod2016      annee typemodif ratio
## 1   14697   14472 2016-01-01         c     1
## 2   01015   01015 2016-01-01         f     1
## 3   01340   01015 2016-01-01         f     1
## 4   01080   01080 2016-01-01         f     1
## 5   01119   01080 2016-01-01         f     1
## 6   01176   01187 2016-01-01         f     1</code></pre>
<p>Les variables des tables sont les suivantes :</p>
<ul>
<li>codXXXX : code Insee de la commune de départ</li>
<li>codYYYY : code Insee de la commune d’arrivée</li>
<li>annee : année de la modification</li>
<li>typemodif : type de modification communale (f = fusion, d = défusion, c= changement de code).</li>
<li>ratio : poids de répartition des effectifs en cas de défusion (vaut 1 sinon). Ce poids est proportionnel à la population des communes défusionnées.</li>
</ul>
<blockquote>
<ul>
<li>DATA_SUPRACOM</li>
</ul>
</blockquote>
<p>Ce Rdata contient, pour chaque année depuis 2014, deux data.frame intitulées table_supracom_20XX et libelles_supracom_20XX qui correspondent aux <a href="https://www.insee.fr/fr/information/2028028">tables d’appartenance des communes aux différents niveaux géographiques</a> produites par l’Insee (cliquez sur le lien pour voir la documentation sur les variables présentes). La première table associe chaque code communal insee aux niveaux supra-communaux associés (en COG le plus actuel, actuellement 2017) et la seconde indique les libellés de ces différents niveaux supra-communaux.</p>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">table_supracom_2017</span><span class="op">)</span></code></pre></div>
<pre><code>##   CODGEO                  LIBGEO DEP REG      EPCI NATURE_EPCI ARR   CV ZE2010
## 1  01001 L'Abergement-Clémenciat  01  84 200069193          CC 012 0108   8213
## 2  01002   L'Abergement-de-Varey  01  84 240100883          CC 011 0101   8201
## 3  01004       Ambérieu-en-Bugey  01  84 240100883          CC 011 0101   8201
## 4  01005     Ambérieux-en-Dombes  01  84 200042497          CC 012 0122   8213
## 5  01006                 Ambléon  01  84 200040350          CC 011 0104   8216
## 6  01007                Ambronay  01  84 240100883          CC 011 0101   8201
##   UU2010 TUU2014 TDUU2014 AU2010 TAU2014 CATAEU2010 BV2012
## 1  01000       0       05    997      00        120  01093
## 2  01000       0       04    002      09        112  01004
## 3  01302       3       32    002      09        112  01004
## 4  01000       0       06    002      09        112  69123
## 5  01000       0       03    998      00        300  01034
## 6  01000       0       07    002      09        112  01004</code></pre>
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">libelles_supracom_2017</span><span class="op">)</span></code></pre></div>
<pre><code>##   NIVGEO CODGEO          LIBGEO NB_COM
## 1    ARR    011          Belley    115
## 2    ARR    012 Bourg-en-Bresse    201
## 3    ARR    013             Gex     27
## 4    ARR    014          Nantua     65
## 5    ARR    021 Château-Thierry    108
## 6    ARR    022            Laon    244</code></pre>
<blockquote>
<ul>
<li>HISTORIQ_MODIF_COM</li>
</ul>
</blockquote>
<p>Ce Rdata contient un data.frame intitulé historiq qui correspond à <a href="https://www.insee.fr/fr/information/2666684#titre-bloc-11">l’historique des géographies communales</a> produit par l’Insee (cliquez sur le lien pour voir la documentation sur les variables présentes). La dernière édition de ce fichier date de 2018 car l’Insee a changé le format de mise à disposition de cette base en 2019 et cette mise à jour n’a pas encore été effectuée dans le package.</p>
</div>
<div id="quel-code-officiel-géographique-est-utilisé" class="section level2">
<h2 class="hasAnchor">
<a href="#quel-code-officiel-g%C3%A9ographique-est-utilis%C3%A9" class="anchor"></a>Quel code officiel géographique est utilisé ?</h2>
<p>Nous allons maintenant manipuler une table exemple incluse dans le package, la table <code>exemple_popcom</code> qui contient comme variables le code géographique de la commune (CODGEO), son nom (LIBGEO), sa population en 2012 (P12_POP), sa superficie (SUPERF) ainsi que deux typologies de territoires générées aléatoirement (typoA et typoB). Il faut veiller à ce que les variables numériques soient au bon format dans R et que les typologies et identifiants soient au format caractère (si ce n’est pas le cas, il faudra les transformer avec les fonctions <em>as.numeric</em> et <em>as.character</em>).</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">)</span></code></pre></div>
<pre><code>##   CODGEO                  LIBGEO P12_POP SUPERF    typoA typoB
## 1  01001 L'Abergement-Clémenciat     777     16 CLASSE 2     F
## 2  01002   L'Abergement-de-Varey     235      9 CLASSE 3     D
## 3  01004       Ambérieu-en-Bugey   14233     25 CLASSE 1     B
## 4  01005     Ambérieux-en-Dombes    1642     16 CLASSE 3     F
## 5  01006                 Ambléon     110      6 CLASSE 4     E
## 6  01007                Ambronay    2437     34 CLASSE 5     A</code></pre>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">)</span></code></pre></div>
<pre><code>## 'data.frame':    36664 obs. of  6 variables:
##  $ CODGEO : chr  "01001" "01002" "01004" "01005" ...
##  $ LIBGEO : chr  "L'Abergement-Clémenciat" "L'Abergement-de-Varey" "Ambérieu-en-Bugey" "Ambérieux-en-Dombes" ...
##  $ P12_POP: int  777 235 14233 1642 110 2437 739 338 1069 385 ...
##  $ SUPERF : int  16 9 25 16 6 34 5 7 29 15 ...
##  $ typoA  : chr  "CLASSE 2" "CLASSE 3" "CLASSE 1" "CLASSE 3" ...
##  $ typoB  : chr  "F" "D" "B" "F" ...
##  - attr(*, "spec")=List of 2
##   ..$ cols   :List of 6
##   .. ..$ CODGEO : list()
##   .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
##   .. ..$ LIBGEO : list()
##   .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
##   .. ..$ P12_POP: list()
##   .. .. ..- attr(*, "class")= chr [1:2] "collector_integer" "collector"
##   .. ..$ SUPERF : list()
##   .. .. ..- attr(*, "class")= chr [1:2] "collector_integer" "collector"
##   .. ..$ typoA  : list()
##   .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
##   .. ..$ typoB  : list()
##   .. .. ..- attr(*, "class")= chr [1:2] "collector_character" "collector"
##   ..$ default: list()
##   .. ..- attr(*, "class")= chr [1:2] "collector_guess" "collector"
##   ..- attr(*, "class")= chr "col_spec"</code></pre>
<div id="cog_akinator" class="section level3">
<h3 class="hasAnchor">
<a href="#cog_akinator" class="anchor"></a><code>COG_akinator</code>
</h3>
<p>La fonction <code>COG_akinator</code> permet de donner des pistes à l’utilisateur sur le code officiel géographique (COG) utilisé dans sa table de données communales, c’est-à-dire de savoir si la liste de communes utilisée correspond à la liste officiel au premier janvier de 2017 ? de 2016 ? ou d’une autre année.</p>
<p>Le paramètre <em>donnees_insee</em> vaut TRUE si les données manipulées sont produites par l’Insee. En effet, quelques rares modifications communales (la défusion des communes Loisey et Culey au 1er janvier 2014 par exemple) ont été prises en compte dans les bases de données communales de l’Insee plus tard que la date officielle (se référer à la documentation de la fonction pour plus de précisions).</p>
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/COG_akinator.html">COG_akinator</a></span><span class="op">(</span>vecteur_codgeo <span class="op">=</span> <span class="va">exemple_popcom</span><span class="op">[</span>,<span class="fl">1</span><span class="op">]</span>, donnees_insee <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "COG2014"</code></pre>
<p>En l’occurrence la liste de communes utilisée dans cette table correspond à la liste des communes au 1er janvier 2014.</p>
</div>
<div id="apparier_cog" class="section level3">
<h3 class="hasAnchor">
<a href="#apparier_cog" class="anchor"></a><code>apparier_COG</code>
</h3>
<p>Une fois que le COG d’une base de données est détecté, ou bien si justement le COG n’arrive pas à être détecté par la fonction <code>COG_akinator</code>, il est possible d’utiliser la fonction <code>apparier_COG</code> pour comparer la liste des communes présente dans une table de données avec le COG d’un millésime donné.</p>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/COG_akinator.html">COG_akinator</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">$</span><span class="va">CODGEO</span>, donnees_insee <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "COG2014"</code></pre>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/apparier_COG.html">apparier_COG</a></span><span class="op">(</span>vecteur_codgeo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">$</span><span class="va">CODGEO</span><span class="op">!=</span><span class="st">"01001"</span><span class="op">)</span>,<span class="fl">1</span><span class="op">]</span>,<span class="st">"XXXXX"</span><span class="op">)</span>,
             donnees_insee <span class="op">=</span> <span class="cn">TRUE</span>, COG <span class="op">=</span> <span class="fl">2014</span><span class="op">)</span></code></pre></div>
<pre><code>## $absent_de_bdd
##  [1] "01001" "97601" "97602" "97603" "97604" "97605" "97606" "97607" "97608"
## [10] "97609" "97610" "97611" "97612" "97613" "97614" "97615" "97616" "97617"
## 
## $absent_de_COG
## [1] "XXXXX"</code></pre>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">appariement</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/apparier_COG.html">apparier_COG</a></span><span class="op">(</span>vecteur_codgeo <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">$</span><span class="va">CODGEO</span><span class="op">!=</span><span class="st">"01001"</span><span class="op">)</span>,<span class="fl">1</span><span class="op">]</span>,<span class="st">"XXXXX"</span><span class="op">)</span>,
                            donnees_insee <span class="op">=</span> <span class="cn">TRUE</span>, COG <span class="op">=</span> <span class="fl">2014</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="va">appariement</span><span class="op">$</span><span class="va">absent_de_bdd</span><span class="op">)</span></code></pre></div>
<pre><code>## 01001 97601 97602 97603 97604 97605 97606 97607 97608 97609 97610 97611 97612 97613 97614 97615 97616 97617</code></pre>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="va">appariement</span><span class="op">$</span><span class="va">absent_de_COG</span><span class="op">)</span></code></pre></div>
<pre><code>## XXXXX</code></pre>
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># regarder le libellé des communes présentes dans le COG mais pas dans la base de données</span>
<span class="va">COG2014_insee</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">COG2014_insee</span><span class="op">$</span><span class="va">CODGEO</span> <span class="op">%in%</span> <span class="va">appariement</span><span class="op">$</span><span class="va">absent_de_bdd</span><span class="op">)</span>,<span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span><span class="op">]</span></code></pre></div>
<pre><code>##       CODGEO                  LIBGEO
## 1      01001 L'Abergement-Clémenciat
## 36665  97601                   Acoua
## 36666  97602              Bandraboua
## 36667  97603                Bandrélé
## 36668  97604                  Bouéni
## 36669  97605                 Chiconi
## 36670  97606               Chirongui
## 36671  97607                 Dembeni
## 36672  97608                Dzaoudzi
## 36673  97609                KaniKéli
## 36674  97610                 Koungou
## 36675  97611               Mamoudzou
## 36676  97612               Mtzamboro
## 36677  97613            Mtsangamouji
## 36678  97614                Ouangani
## 36679  97615                Pamandzi
## 36680  97616                    Sada
## 36681  97617                Tsingoni</code></pre>
</div>
<div id="diag_cog" class="section level3">
<h3 class="hasAnchor">
<a href="#diag_cog" class="anchor"></a><code>diag_COG</code>
</h3>
<p>Enfin, la fonction <code>diag_COG</code> permet de vous outiller encore davantage. Elle réalise un diagnostic complet du ou des COG présents dans votre base de données.</p>
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">diagnostic</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/diag_COG.html">diag_COG</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "# ------------------------------"
## [1] "# DIAGNOSTIC DE COG"
## [1] "# ------------------------------"
## [1] "# Synthèse"
## [1] "# COG2014"
## [1] "# ------------------------------"
## [1] "# Diagnostic détaillé"
## [1] "# Le fichier compte 36664 codes communes."
## [1] "# Le diagnostic de COG correspond au COG le plus récent dans lequel l'ensemble des codes communes du fichier en entrée sont présents."
## 
## 
## |              | Nombre d'observations|
## |:-------------|---------------------:|
## |COG2014       |                 36664|
## |codes uniques |                 36664|</code></pre>
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">diagnostic</span><span class="op">)</span></code></pre></div>
<pre><code>##   CODGEO diag_cog                  LIBGEO P12_POP SUPERF    typoA typoB
## 1  01001  COG2014 L'Abergement-Clémenciat     777     16 CLASSE 2     F
## 2  01002  COG2014   L'Abergement-de-Varey     235      9 CLASSE 3     D
## 3  01004  COG2014       Ambérieu-en-Bugey   14233     25 CLASSE 1     B
## 4  01005  COG2014     Ambérieux-en-Dombes    1642     16 CLASSE 3     F
## 5  01006  COG2014                 Ambléon     110      6 CLASSE 4     E
## 6  01007  COG2014                Ambronay    2437     34 CLASSE 5     A</code></pre>
<p>Ici le diagnostic nous montre que la base de données est bien construite puisqu’elle ne comporte que des codes communes d’une même année, 2014.</p>
<p>Mais cette fonction permet également de diagnostiquer des bases de données qui comportent des mix entre plusieurs COG (oh, horreur !) comme dans l’exemple ci-dessous :</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_popcom_deforme</span> <span class="op">&lt;-</span> <span class="va">exemple_popcom</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://tibble.tidyverse.org/reference/add_row.html">add_row</a></span><span class="op">(</span>CODGEO <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/rep.html">rep</a></span><span class="op">(</span><span class="st">"01001"</span>,<span class="fl">5</span><span class="op">)</span>,<span class="st">"14666"</span>,<span class="st">"75101"</span>,<span class="cn">NA</span>,<span class="st">"98756"</span>,<span class="st">"ZZZZZ"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">diagnostic2</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/diag_COG.html">diag_COG</a></span><span class="op">(</span><span class="va">exemple_popcom_deforme</span><span class="op">)</span></code></pre></div>
<pre><code>[1] "# ------------------------------"
[1] "# DIAGNOSTIC DE COG"
[1] "# ------------------------------"
[1] "# Synthèse"
[1] "# COG non identifiable"
[1] "# ------------------------------"
[1] "# Diagnostic détaillé"
[1] "# Le fichier compte 36674 codes communes."
[1] "# Dans la mesure où le COG n'est pas identifiable, le diagnostic de COG correspond au COG le plus récent d'apparition de chaque code commune du fichier en entrée."


|                         | Nombre d'observations|
|:------------------------|---------------------:|
|COG2021                  |                 34952|
|COG2015                  |                   773|
|COG2016                  |                   467|
|COG2018                  |                   387|
|COG2017                  |                    59|
|COG2014                  |                    25|
|COG2020                  |                     4|
|COG2019                  |                     3|
|arrondissement municipal |                     1|
|code indéterminé         |                     1|
|code manquant            |                     1|
|collectivité d'outre-mer |                     1|
|codes uniques            |                 36668|</code></pre>
<p>La fonction <code>diag_COG</code> ne reconnaissant pas le COG, elle identifie pour chaque ligne de la table, l’année la plus récente d’apparition de la commune dans les tables de COG.</p>
<p>Toutefois, lorsque le COG est relativement ancien, comme ici 2014, il n’est pas évident à partir de cela d’en déduire qu’il s’agit d’une table millésimée 2014 avec simplement quelques lignes erronées dedans puisque <code>diag_COG</code> identifie en priorité les COG récents. Dans ce cas, la fonction <code>COG_akinator</code> vue précédemment peut vous aider à identifier le millésime 2014 de par son approche complémentaire à <code>diag_COG</code> :</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/COG_akinator.html">COG_akinator</a></span><span class="op">(</span><span class="va">exemple_popcom_deforme</span><span class="op">$</span><span class="va">CODGEO</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] "COG2014"</code></pre>
</div>
</div>
<div id="visualiser-les-modifications-communales" class="section level2">
<h2 class="hasAnchor">
<a href="#visualiser-les-modifications-communales" class="anchor"></a>Visualiser les modifications communales</h2>
<p>La fonction <code>trajectoire_commune</code> permet d’observer sur un diagramme interactif la trajectoire d’une commune depuis 1968 (aucun changement, fusions, défusions ou changements de codes).</p>
<p>Le paramètre <em>codgeo</em> est une chaîne de 5 caractères qui indique le code Insee de la commune considérée et le paramètre <em>COG</em> indique l’année de COG de la communes considérée.</p>
<p>La fonction <code>trajectoire_commune_shiny</code> lance une application shiny qui permet de sélectionner la commune pour laquelle vous souhaitez observer ses modifications depuis 1968.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ici, nous allons observer sur un graphique interactif la trajectoire de la commune ayant pour code 01003 en 1968</span>
<span class="co"># (fusion avec 2 autres communes le 1er janvier 1974)</span>
<span class="fu"><a href="../reference/trajectoire_commune.html">trajectoire_commune</a></span><span class="op">(</span><span class="st">"01003"</span>, <span class="fl">1968</span>, donnees_insee <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
<div id="htmlwidget-d48343eb3fa97ddf2840" style="width:100%;height:500px;" class="visNetwork html-widget"></div>
<script type="application/json" data-for="htmlwidget-d48343eb3fa97ddf2840">{"x":{"nodes":{"id":["01003_1968","01070_1968","01165_1968","01165_1975","01165_2021"],"comm":["01003","01070","01165","01165","01165"],"COG":["1968","1968","1968","1975","2021"],"label":["01003\n(1968)","01070\n(1968)","01165\n(1968)","01165\n(1975)","01165\n(2021)"],"level":[1,1,1,2,3],"pop":["140","100","128","470","1603"],"libgeo":["AMAREINS","CESSEINS","FRANCHELEINS","FRANCHELEINS","Francheleins"],"ratio":[1,1,1,1,1],"title":["<b><a target=\"_blank\" href=https://www.insee.fr/fr/recherche/recherche-geographique?geo=COM-01003&debut=0>01003<\/a> AMAREINS<\/b><br>Population : 140 hab.","<b><a target=\"_blank\" href=https://www.insee.fr/fr/recherche/recherche-geographique?geo=COM-01070&debut=0>01070<\/a> CESSEINS<\/b><br>Population : 100 hab.","<b><a target=\"_blank\" href=https://www.insee.fr/fr/recherche/recherche-geographique?geo=COM-01165&debut=0>01165<\/a> FRANCHELEINS<\/b><br>Population : 128 hab.","<b><a target=\"_blank\" href=https://www.insee.fr/fr/recherche/recherche-geographique?geo=COM-01165&debut=0>01165<\/a> FRANCHELEINS<\/b><br>Population : 470 hab.","<b><a target=\"_blank\" href=https://www.insee.fr/fr/recherche/recherche-geographique?geo=COM-01165&debut=0>01165<\/a> Francheleins<\/b><br>Population : 1603 hab."]},"edges":{"from":["01003_1968","01070_1968","01165_1968","01165_1975"],"to":["01165_1975","01165_1975","01165_1975","01165_2021"],"LIBGEO":["AMAREINS","CESSEINS","FRANCHELEINS",null],"POP":[140,100,128,null],"annee":["1974-01-01","1974-01-01","1974-01-01",null],"typemodif":["f","f","f",null],"ratio":[1,1,1,1],"arrows.middle.enabled":[true,true,true,false],"dashes":[false,false,false,true],"value":[1,1,1,0.2],"title":["<b>fusion<\/b><br>Date : 01 janv. 1974<br>","<b>fusion<\/b><br>Date : 01 janv. 1974<br>","<b>fusion<\/b><br>Date : 01 janv. 1974<br>",null]},"nodesToDataframe":true,"edgesToDataframe":true,"options":{"width":"100%","height":"100%","nodes":{"shape":"ellipse","color":{"border":"black","background":"#000000","highlight":{"border":"#000000","background":"#000000"}},"fixed":{"allowedToMoveX":true,"allowedToMoveY":true},"font":{"face":"verdana","color":"#FFFFFF","size":20}},"manipulation":{"enabled":false},"edges":{"width":10,"arrows":{"middle":{"enabled":true,"scaleFactor":3}},"color":{"color":"#2AA198"},"shadow":false},"layout":{"hierarchical":{"enabled":true,"levelSeparation":500,"direction":"LR"},"randomSeed":12},"interaction":{"hoverConnectedEdges":false,"navigationButtons":true,"selectable":false,"selectConnectedEdges":false},"physics":{"hierarchicalRepulsion":{"centralGravity":0,"springConstant":0,"nodeDistance":0}},"configure":{"enabled":false}},"groups":null,"width":"100%","height":"500px","idselection":{"enabled":false},"byselection":{"enabled":false},"main":null,"submain":null,"footer":null,"background":"rgba(0, 0, 0, 0)","tooltipStay":300,"tooltipStyle":"position: fixed;visibility:hidden;padding: 5px;white-space: nowrap;font-family: verdana;font-size:14px;font-color:#000000;background-color: #f5f4ed;-moz-border-radius: 3px;-webkit-border-radius: 3px;border-radius: 3px;border: 1px solid #808074;box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.2);"},"evals":[],"jsHooks":[]}</script><div class="sourceCode" id="cb40"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Cette fonction lance une application shiny permettant d'observer toutes les trajectoires des communes.</span>
<span class="co">#trajectoire_commune_shiny()</span></code></pre></div>
<p>La fonction <code>modifications_communales</code> permet, comme son nom l’indique, de visualiser les modifications communales (fusions, défusions, changements de codes ou de noms) qui ont eu lieu entre deux dates. Ici entre le 01/01/2014 et le 01/01/2015. Cette fonction est encore en cours de développement il est donc possible que certains évènements ne soient pas encore pris en compte. Il ne faut pas hésiter à le signaler.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">modifs</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/modifications_communales.html">modifications_communales</a></span><span class="op">(</span>date_debut <span class="op">=</span> <span class="st">"01-01-2014"</span>, date_fin <span class="op">=</span> <span class="st">"01-01-2015"</span><span class="op">)</span></code></pre></div>
<pre><code>## Warning: En raison d'un changement de fichier d'historique de l'Insee en 2019,
## cette fonction n'est à ce stade plus maintenue pour les millésimes après 2018.</code></pre>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="va">modifs</span><span class="op">$</span><span class="va">fusions</span><span class="op">)</span></code></pre></div>
<pre><code>## 2015-01-01 : Notre-Dame-d'Estrées-Corbon (14474) est un rassemblement de Corbon (14178), Notre-Dame-d'Estrées (14474) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Auxons (25035) est un rassemblement de Auxon-Dessous (25034), Auxon-Dessus (25035) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Goussainville (28185) est un rassemblement de Champagne (28069), Goussainville (28185) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Eclose-Badinières (38152) est un rassemblement de Badinières (38024), Eclose (38152) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Saint-Crépin-Ibouvillers (60570) est un rassemblement de Montherlant (60417), Saint-Crépin-Ibouvillers (60570) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Montsecret-Clairefougère (61292) est un rassemblement de Clairefougère (61109), Montsecret (61292) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Boischampré (61375) est un rassemblement de Marcei (61249), Saint-Christophe-le-Jajolet (61375), Saint-Loyer-des-Champs (61417), Vrigny (61511) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Tinchebray-Bocage (61486) est un rassemblement de Beauchêne (61031), Frênes (61177), Larchamp (61223), Saint-Cornier-des-Landes (61377), Saint-Jean-des-Bois (61410), Tinchebray (61486), Yvrandes (61513) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Vaugneray (69255) est un rassemblement de Saint-Laurent-de-Vaux (69221), Vaugneray (69255) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Clux-Villeneuve (71578) est un rassemblement de Clux (71138), Villeneuve (71578) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Villeneuve-en-Perseigne (72137) est un rassemblement de Chassé (72069), Fresnaye-sur-Chédouet (72137), Lignières-la-Carelle (72162), Montigny (72207), Roullée (72258), Saint-Rigomer-des-Bois (72318) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Saint-Offenge (73263) est un rassemblement de Saint-Offenge-Dessous (73263), Saint-Offenge-Dessus (73264) [commune nouvelle avec commune(s) déléguée(s)].
## 2015-01-01 : Orvanne (77316) est un rassemblement de Écuelles (77166), Moret-sur-Loing (77316) [commune nouvelle avec commune(s) déléguée(s)].</code></pre>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="va">modifs</span><span class="op">$</span><span class="va">defusions</span><span class="op">)</span></code></pre></div>
<pre><code>## ATTENTION, l'évènement suivant a été pris en compte dans les données de l'Insee seulement au 01/01/2015 : 2014-01-01 : Loisey (55298) s'est séparée en Loisey (55298), Culey (55138) [rétablissement].</code></pre>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="va">modifs</span><span class="op">$</span><span class="va">changements_codes</span><span class="op">)</span></code></pre></div>
<pre><code>## 2014-01-07 : Le code commune de Oudon passe de 14697 à 14472 [changement de code dû à un changement de chef-lieu].</code></pre>
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/cat.html">cat</a></span><span class="op">(</span><span class="va">modifs</span><span class="op">$</span><span class="va">changements_noms</span><span class="op">)</span></code></pre></div>
<pre><code>## 2014-12-06 : La commune de Barisis (02049) change de nom en Barisis-aux-Bois [changement de nom].
## 2014-12-06 : La commune de Sainte-Colombe (21544) change de nom en Sainte-Colombe-en-Auxois [changement de nom].
## 2014-12-06 : La commune de Pont-de-Roide (25463) change de nom en Pont-de-Roide-Vermondans [changement de nom].
## 2014-12-06 : La commune de Cazaril-Laspènes (31129) change de nom en Cazarilh-Laspènes [changement de nom].
## 2014-12-06 : La commune de Saint-Martin (66184) change de nom en Saint-Martin-de-Fenouillet [changement de nom].
## 2014-12-06 : La commune de Cré (72108) change de nom en Cré-sur-Loir [changement de nom].
## 2014-12-06 : La commune de Belbèse (82015) change de nom en Belbèze-en-Lomagne [changement de nom].
## 2014-12-06 : La commune de Saint-Vincent (82174) change de nom en Saint-Vincent-d'Autéjac [changement de nom].</code></pre>
</div>
<div id="transformer-des-variables-numériques-en-autre-géographie" class="section level2">
<h2 class="hasAnchor">
<a href="#transformer-des-variables-num%C3%A9riques-en-autre-g%C3%A9ographie" class="anchor"></a>Transformer des variables numériques en autre géographie</h2>
<p>La fonction <code>changement_COG_varNum</code> permet de transformer des tables de données numériques communales en géographie au premier janvier d’une année souhaitée.</p>
<p>Ici, nous allons transformer les variables numériques de la table <em>exemple_pop</em> afin de récupérer les données de population et de superficie des communes au 1er janvier 2017 (au lieu de 2014).</p>
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_popcom_COG2017_num</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/changement_COG_varNum.html">changement_COG_varNum</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_popcom</span>, annees <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2014</span><span class="op">:</span><span class="fl">2017</span><span class="op">)</span>,
                                                    agregation <span class="op">=</span> <span class="cn">TRUE</span>, libgeo <span class="op">=</span> <span class="cn">TRUE</span>, donnees_insee <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_popcom_COG2017_num</span><span class="op">)</span></code></pre></div>
<pre><code>##   CODGEO             nom_commune P12_POP SUPERF
## 1  01001 L'Abergement-Clémenciat     777     16
## 2  01002   L'Abergement-de-Varey     235      9
## 3  01004       Ambérieu-en-Bugey   14233     25
## 4  01005     Ambérieux-en-Dombes    1642     16
## 5  01006                 Ambléon     110      6
## 6  01007                Ambronay    2437     34</code></pre>
<p>Le paramètre <em>agregation</em> vaut TRUE si la table souhaitée doit sommer toutes les lignes qui concernent une même commune et FALSE si l’on souhaite volontairement conserver les doublons dans les codes commune (dans les tables de flux par exemple, cf. plus bas). Le paramètre <em>libgeo</em> vaut TRUE si l’on veut rajouter dans la table une colonne nommée “nom_commune” qui indique le nom de la commune issu du code officiel géographique et FALSE sinon.</p>
</div>
<div id="transformer-des-typologies-en-autre-géographie" class="section level2">
<h2 class="hasAnchor">
<a href="#transformer-des-typologies-en-autre-g%C3%A9ographie" class="anchor"></a>Transformer des typologies en autre géographie</h2>
<p>La fonction <code>changement_COG_typo</code> permet de transformer des typologies de communes en géographie au premier janvier d’une année souhaitée. Ici nous allons transformer les deux typologies (typoA et typoB) de la table <em>exemple_pop</em> en géographie communale au 1er janvier 2017 (au lieu de 2014).</p>
<p>Ici, l’hypothèse de classement en cas de fusion de communes (<em>methode_fusion</em>) choisie est celle d’une classe spécifique (<em>methode_difference</em>, classe appelée <em>mot_difference</em>=“differents”) aux regroupements de plusieurs communes de classes différentes. Les autres hypothèses possibles auraient pu être l’hypothèse du maximum de population <em>methode_max_pop</em>, de classe absorbée <em>methode_classe_absorbee</em>, de classe absorbante <em>methode_classe_absorbante</em> ou d’indiquer un nom de classe spécifique pour toutes les communes qui ont fusionnées : <em>methode_classe_fusion</em>. Pour plus de détails, référez-vous à ?changement_COG_typo.</p>
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_popcom_COG2017_typo</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/changement_COG_typo.html">changement_COG_typo</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_popcom</span><span class="op">[</span>,<span class="op">-</span><span class="fl">2</span><span class="op">]</span>, annees <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2014</span><span class="op">:</span><span class="fl">2017</span><span class="op">)</span>,
                                                   methode_fusion <span class="op">=</span> <span class="st">"methode_difference"</span>, typos <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"typoA"</span>,<span class="st">"typoB"</span><span class="op">)</span>,
                                                   mot_difference <span class="op">=</span> <span class="st">"differents"</span>, libgeo<span class="op">=</span><span class="cn">TRUE</span>,
                                                   donnees_insee<span class="op">=</span><span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_popcom_COG2017_typo</span><span class="op">)</span></code></pre></div>
<pre><code>##   CODGEO             nom_commune    typoA typoB
## 1  01001 L'Abergement-Clémenciat CLASSE 2     F
## 2  01002   L'Abergement-de-Varey CLASSE 3     D
## 3  01004       Ambérieu-en-Bugey CLASSE 1     B
## 4  01005     Ambérieux-en-Dombes CLASSE 3     F
## 5  01006                 Ambléon CLASSE 4     E
## 6  01007                Ambronay CLASSE 5     A</code></pre>
<p>La fonction <code>changement_COG_typo_details</code> permet quant à elle d’isoler dans une table les communes fusionnées appartenant à des classes différentes, ici selon la typologie “typoA” entre 2014 et 2015 puis 2015 et 2016 et 2016 et 2017.</p>
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">details_exemple_popcom_COG2017_typo</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/changement_COG_typo_details.html">changement_COG_typo_details</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_popcom</span><span class="op">[</span>,<span class="op">-</span><span class="fl">2</span><span class="op">]</span>,
                                                                   annees <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2014</span><span class="op">:</span><span class="fl">2017</span><span class="op">)</span>, typo <span class="op">=</span> <span class="st">"typoA"</span>,
                                                                   donnees_insee <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">details_exemple_popcom_COG2017_typo</span><span class="op">[[</span><span class="st">"2014_2015"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>##   cod2014              lib2014 cod2015                     lib2015    typoA
## 1   14178               Corbon   14474 Notre-Dame-d'Estrées-Corbon CLASSE 2
## 2   14474 Notre-Dame-d'Estrées   14474 Notre-Dame-d'Estrées-Corbon CLASSE 4
## 3   25034        Auxon-Dessous   25035                  Les Auxons CLASSE 1
## 4   25035         Auxon-Dessus   25035                  Les Auxons CLASSE 3
## 5   38024           Badinières   38152           Eclose-Badinières CLASSE 4
## 6   38152               Eclose   38152           Eclose-Badinières CLASSE 3</code></pre>
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">details_exemple_popcom_COG2017_typo</span><span class="op">[[</span><span class="st">"2015_2016"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>##   cod2015             lib2015 cod2016            lib2016    typoA
## 1   01015           Arbignieu   01015    Arboys en Bugey CLASSE 3
## 2   01340          Saint-Bois   01015    Arboys en Bugey CLASSE 2
## 3   01119           Corcelles   01080 Champdor-Corcelles CLASSE 1
## 4   01080            Champdor   01080 Champdor-Corcelles CLASSE 2
## 5   01176 Le Grand-Abergement   01187      Haut Valromey CLASSE 2
## 6   01409             Songieu   01187      Haut Valromey CLASSE 5</code></pre>
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">details_exemple_popcom_COG2017_typo</span><span class="op">[[</span><span class="st">"2016_2017"</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>##   cod2016             lib2016 cod2017          lib2017    typoA
## 1   01095 Chavannes-sur-Suran   01095 Nivigne et Suran CLASSE 5
## 2   01172           Germagnat   01095 Nivigne et Suran CLASSE 1
## 3   01098         Chazey-Bons   01098      Chazey-Bons CLASSE 3
## 4   01316              Pugieu   01098      Chazey-Bons CLASSE 4
## 5   03168             Meaulne   03168   Meaulne-Vitray CLASSE 2
## 6   03318              Vitray   03168   Meaulne-Vitray CLASSE 5</code></pre>
</div>
<div id="agréger-des-tables-de-données-communales-à-des-échelons-supra-communaux" class="section level2">
<h2 class="hasAnchor">
<a href="#agr%C3%A9ger-des-tables-de-donn%C3%A9es-communales-%C3%A0-des-%C3%A9chelons-supra-communaux" class="anchor"></a>Agréger des tables de données communales à des échelons supra-communaux</h2>
<p>La fonction <code>nivsupra</code> permet d’agréger les tables de données communales à de nombreux échelons supra-communaux administratifs (EPCI, arrondissements, cantons-villes, départements, régions) ou d’étude (bassins de vie, zones d’emploi, unités urbaines, aires urbaines) en indiquant le COG de la base de donnée en entrée et de référence des niveaux supra-communaux grâce au paramètre <em>COG</em> (par défaut vaut la valeur de <code>annee_ref</code>, la plus récente valeur contenue dans le package). Le paramètre <em>COG</em> peut prendre les valeurs 2008 à <code>annee_ref</code>.</p>
<p>Ici nous agrégeons la population et la superficie des communes à l’échelon géographique des zones d’emploi afin d’obtenir une table des densités de population par zone d’emploi.</p>
<div class="sourceCode" id="cb61"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_popcom_COG2017</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/merge.html">merge</a></span><span class="op">(</span><span class="va">exemple_popcom_COG2017_num</span>, <span class="va">exemple_popcom_COG2017_typo</span><span class="op">[</span>,<span class="op">-</span><span class="fl">2</span><span class="op">]</span>, by <span class="op">=</span> <span class="st">"CODGEO"</span>,
                                all <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">exemple_popcom_ZE2010</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/nivsupra.html">nivsupra</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_popcom_COG2017</span>, nivsupra<span class="op">=</span><span class="st">"ZE2010"</span>, agregation <span class="op">=</span> <span class="cn">TRUE</span>,
                                  COG <span class="op">=</span> <span class="fl">2017</span><span class="op">)</span>
<span class="va">exemple_popcom_ZE2010</span><span class="op">$</span><span class="va">densite</span> <span class="op">&lt;-</span> <span class="va">exemple_popcom_ZE2010</span><span class="op">$</span><span class="va">P12_POP</span> <span class="op">/</span> <span class="va">exemple_popcom_ZE2010</span><span class="op">$</span><span class="va">SUPERF</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_popcom_ZE2010</span><span class="op">)</span></code></pre></div>
<pre><code>##   ZE2010                         LIBGEO P12_POP SUPERF  densite
## 1   0050                 Mont-de-Marsan  160717   4956 32.42877
## 2   0051                        Alençon  122263   2405 50.83701
## 3   0052                Cosne - Clamecy   75052   2553 29.39757
## 4   0053                          Mâcon  143358   1543 92.90862
## 5   0054               Nogent-le-Rotrou   48665   1227 39.66178
## 6   0055 La Vallée de la Bresle - Vimeu   99095   1134 87.38536</code></pre>
</div>
<div id="gérer-des-cas-particuliers-dans-les-bases-de-données" class="section level2">
<h2 class="hasAnchor">
<a href="#g%C3%A9rer-des-cas-particuliers-dans-les-bases-de-donn%C3%A9es" class="anchor"></a>Gérer des cas particuliers dans les bases de données</h2>
<div id="enlever-les-arrondissements-municipaux-des-tables-de-données-communales" class="section level3">
<h3 class="hasAnchor">
<a href="#enlever-les-arrondissements-municipaux-des-tables-de-donn%C3%A9es-communales" class="anchor"></a>Enlever les arrondissements municipaux des tables de données communales</h3>
<p>Nous allons maintenant manipuler une autre table exemple incluse dans le package, la table <code>exemple_flux</code> qui contient des exemples de flux entre une communes de résidences (COMMUNE) et de travail (DCLT). Elle contient comme autres variables le code de la catégorie socio-professionnelle des individus (CS1), la catégorie d’âge (AGEREVQ) et le poids de l’individu statistique (IPONDI).</p>
<div class="sourceCode" id="cb63"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_flux</span><span class="op">)</span></code></pre></div>
<pre><code>##   COMMUNE  DCLT CS1 AGEREVQ IPONDI
## 1   55298 45055   5      25      4
## 2   55298 52448   3      50      4
## 3   55298 54323   5      55      4
## 4   55298 55010   6      35      4
## 5   55298 55029   6      20      4
## 6   55298 55029   6      40      4</code></pre>
<p>La fonction <code>enlever_PLM</code> permet de remplacer les codes Insee des arrondissements municipaux de Paris, Lyon et Marseille par leurs codes communes respectifs.</p>
<p>Le paramètre <em>vecteur_entree</em> vaut TRUE si l’élément à transformer est un vecteur de codes insee et FALSE s’il s’agit d’une table de données (data.frame) numériques. Attention, cette fonction ne gère pas les conversions de typologies (variables de type caractère).</p>
<p>Ici nous allons remplacer les arrondissement municipaux par les codes communaux dans la table <code>exemple_flux</code> pour les variables COMMUNE puis DCLT.</p>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_flux_sansPLM</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/enlever_PLM.html">enlever_PLM</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_flux</span>, codgeo_entree <span class="op">=</span> <span class="st">"COMMUNE"</span>, libgeo <span class="op">=</span> <span class="cn">NULL</span>,
                                    agregation <span class="op">=</span> <span class="cn">FALSE</span>, vecteur_entree <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span>
<span class="va">exemple_flux_sansPLM</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/enlever_PLM.html">enlever_PLM</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_flux_sansPLM</span>, codgeo_entree <span class="op">=</span> <span class="st">"DCLT"</span>, libgeo <span class="op">=</span> <span class="cn">NULL</span>,
                                    agregation <span class="op">=</span> <span class="cn">FALSE</span>, vecteur_entree <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></code></pre></div>
</div>
<div id="jongler-avec-les-différentes-possibilités-pour-les-codes-communaux-corses" class="section level3">
<h3 class="hasAnchor">
<a href="#jongler-avec-les-diff%C3%A9rentes-possibilit%C3%A9s-pour-les-codes-communaux-corses" class="anchor"></a>Jongler avec les différentes possibilités pour les codes communaux corses</h3>
<p>La fonction <code>modification_Corse</code> permet quant à elle de modifier les codes Insee des communes corses. En effet, en 1976, les codes de toutes les communes corses sont modifiés : alors qu’ils commençaient tous par “20”, leurs deux premiers caractères sont remplacés par “2A” (Corse du Sud) ou “2B” (Corse du Nord). Les codes postaux conservent d’ailleurs aujourd’hui le préfixe historique “20”. Cette fonction est notamment utile pour la raison suivante : dans certaines tables issues des recensements Insee de 1968 ou 1975, les communes sont déjà codées avec les préfixes 2A et 2B.</p>
<p>Le paramètre <em>sens</em> vaut “20vers2A2B” pour changer tous les codes communes corses commençant par 20 par 2A ou 2B et vaut “2A2Bvers20” quand l’effet inverse est recherché.</p>
<div class="sourceCode" id="cb66"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_flux_sansPLMsansCorse</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/modification_Corse.html">modification_Corse</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_flux_sansPLM</span>, sens <span class="op">=</span> <span class="st">"2A2Bvers20"</span><span class="op">)</span></code></pre></div>
</div>
<div id="corriger-le-code-commune-de-loudon-dans-le-calvados" class="section level3">
<h3 class="hasAnchor">
<a href="#corriger-le-code-commune-de-loudon-dans-le-calvados" class="anchor"></a>Corriger le code commune de l’Oudon dans le Calvados</h3>
<p>La fonction <code>modification_Oudon</code> permet de modifier les codes Insee de l’ancienne commune de l’Oudon (Calvados, 14). Cette commune a connu une modification assez rare (transfert de chef-lieu) qui implique donc parfois des erreurs de codage de la commune dans certaines bases de données. En effet, la commune de l’Oudon a toujours été codée “14697” puis a changé de code devenant “14472” à partir du 07/01/2014 suite à un transfert de chef lieu. Cette commune a depuis disparu puisqu’elle est devenue commune déléguée au sein de Saint-Pierre-en-Auge (14654).</p>
<div class="sourceCode" id="cb67"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># Ici, nous allons remplacer les codes communes de l'Oudon dans une table de l'Insee</span>
<span class="co"># (en COG 2014 mais que nous considérons en COG 2015 uniquement pour cet exemple).</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">$</span><span class="va">CODGEO</span> <span class="op">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"14472"</span>,<span class="st">"14697"</span><span class="op">)</span><span class="op">)</span>,<span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>##      CODGEO  LIBGEO P12_POP SUPERF    typoA typoB
## 5159  14697 L'Oudon    1551     55 CLASSE 1     D</code></pre>
<div class="sourceCode" id="cb69"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_popcom_oudon</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/modification_Oudon.html">modification_Oudon</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_popcom</span>,
                                           donnees_insee_entree <span class="op">=</span> <span class="cn">TRUE</span>, donnees_insee_sortie <span class="op">=</span> <span class="cn">FALSE</span>, COG <span class="op">=</span> <span class="fl">2015</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_popcom_oudon</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/which.html">which</a></span><span class="op">(</span><span class="va">exemple_popcom</span><span class="op">$</span><span class="va">CODGEO</span><span class="op">%in%</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"14472"</span>,<span class="st">"14697"</span><span class="op">)</span><span class="op">)</span>,<span class="op">]</span><span class="op">)</span></code></pre></div>
<pre><code>##      CODGEO  LIBGEO P12_POP SUPERF    typoA typoB
## 5159  14472 L'Oudon    1551     55 CLASSE 1     D</code></pre>
</div>
</div>
<div id="transformer-des-variables-numériques-en-autre-géographie-dans-des-données-de-flux" class="section level2">
<h2 class="hasAnchor">
<a href="#transformer-des-variables-num%C3%A9riques-en-autre-g%C3%A9ographie-dans-des-donn%C3%A9es-de-flux" class="anchor"></a>Transformer des variables numériques en autre géographie dans des données de flux</h2>
<p>La fonction <code>changement_COG_varNum</code> peut également s’appliquer à des tables de flux (codes communes pouvant comporter des doublons) grâce à l’option agregation = FALSE. Les variables de type caractère sont alors conservées comme telles ou dupliquées en cas de défusion et les variables numériques (ici IPONDI) sommées en cas de fusion ou réparties proportionnellement à la population de chaque commune en cas de défusion.</p>
<div class="sourceCode" id="cb71"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_flux_COG2017</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/changement_COG_varNum.html">changement_COG_varNum</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_flux_sansPLMsansCorse</span>,
                                              annees <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2014</span><span class="op">:</span><span class="fl">2017</span><span class="op">)</span>, codgeo_entree <span class="op">=</span> <span class="st">"COMMUNE"</span>, agregation <span class="op">=</span> <span class="cn">FALSE</span>,
                                              libgeo <span class="op">=</span> <span class="cn">FALSE</span>, donnees_insee <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>
<span class="va">exemple_flux_COG2017</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/changement_COG_varNum.html">changement_COG_varNum</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_flux_COG2017</span>,
                                              annees <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">2014</span><span class="op">:</span><span class="fl">2017</span><span class="op">)</span>, codgeo_entree <span class="op">=</span> <span class="st">"DCLT"</span>,
                                              agregation <span class="op">=</span> <span class="cn">FALSE</span>, libgeo <span class="op">=</span> <span class="cn">FALSE</span>, donnees_insee <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></code></pre></div>
</div>
<div id="insérer-dans-des-tables-de-données-de-flux-communales-des-échelons-supra-communaux" class="section level2">
<h2 class="hasAnchor">
<a href="#ins%C3%A9rer-dans-des-tables-de-donn%C3%A9es-de-flux-communales-des-%C3%A9chelons-supra-communaux" class="anchor"></a>Insérer dans des tables de données de flux communales des échelons supra-communaux</h2>
<p>La fonction <code>nivsupra</code> peut également s’appliquer à des tables de flux (non agrégées par codes communes) grâce à l’option agregation = FALSE. La table en entrée est alors conservée comme telle avec une nouvelle colonne qui correspond au niveau supracommunal du code commune considéré.</p>
<p>Ici, on ajoute les colonnes ZE2010_COMMUNE et ZE2010_DCLT à la table de flux domicile-travail utilisée précédemment.</p>
<div class="sourceCode" id="cb72"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">exemple_flux_COG2017_etZE</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/nivsupra.html">nivsupra</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_flux_COG2017</span>, codgeo_entree <span class="op">=</span> <span class="st">"COMMUNE"</span>,
                                      nivsupra <span class="op">=</span> <span class="st">"ZE2010"</span>, agregation <span class="op">=</span> <span class="cn">FALSE</span>, COG <span class="op">=</span> <span class="fl">2017</span><span class="op">)</span>
<span class="va">exemple_flux_COG2017_etZE</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/nivsupra.html">nivsupra</a></span><span class="op">(</span>table_entree <span class="op">=</span> <span class="va">exemple_flux_COG2017_etZE</span>, codgeo_entree <span class="op">=</span> <span class="st">"DCLT"</span>,
                                      nivsupra <span class="op">=</span> <span class="st">"ZE2010"</span>, agregation <span class="op">=</span> <span class="cn">FALSE</span>, COG <span class="op">=</span> <span class="fl">2017</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">exemple_flux_COG2017_etZE</span><span class="op">)</span></code></pre></div>
<pre><code>##   COMMUNE  DCLT CS1 AGEREVQ   IPONDI ZE2010_COMMUNE ZE2010_nom_COMMUNE
## 1   61001 61001   4      25 2.856389           0051            Alençon
## 2   61001 61001   3      55 3.040441           0051            Alençon
## 3   61213 53185   2      40 4.142349           0051            Alençon
## 4   61203 61001   5      25 5.234542           0051            Alençon
## 5   61491 61500   5      40 5.578419           0051            Alençon
## 6   61077 61117   4      35 4.153005           0051            Alençon
##   ZE2010_DCLT ZE2010_nom_DCLT
## 1        0051         Alençon
## 2        0051         Alençon
## 3        0051         Alençon
## 4        0051         Alençon
## 5        0051         Alençon
## 6        0051         Alençon</code></pre>
<p>Bonne découverte…!</p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Kim Antunez.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
